#!/usr/bin/env python3
"""
bake_asset.py -- FALLOUT GPU asset baker (spec section 5).

Converts a PNG into an RGB 3-3-2 C header for the 160x120 discrete-logic GPU
framebuffer. Pixel packing matches the GPU/firmware exactly:

    rgb332 = (r & 0xE0) | ((g & 0xE0) >> 3) | ((b & 0xC0) >> 6)

Bytes are emitted row-major (index = y * W + x), 16 bytes per line, wrapped in
an include guard with <NAME>_W / <NAME>_H defines.

Usage:
    python bake_asset.py INPUT.png [-o OUT.h] [--width 160] [--height 120]
                         [--name ARRAYNAME] [--preview PREVIEW.png]
                         [--resample nearest|lanczos]

Options:
    -o OUT.h           Output header path (default: INPUT basename + .h)
    --width/--height   Target size (default 160x120, the GPU framebuffer)
    --name NAME        C array name (default: derived from output filename)
    --preview FILE     Also write the quantized result back out as an upscaled
                       PNG (332 decoded with high-bit replication) so you can
                       preview the 8-bit look on the laptop.
    --resample MODE    'lanczos' (default, photos) or 'nearest' (pixel art).

Examples:
    python bake_asset.py vaultboy.png
    python bake_asset.py sprite.png -o sprite.h --name SPRITE --resample nearest
    python bake_asset.py photo.png --preview photo_332.png
"""

import argparse
import os
import re
import sys

from PIL import Image


def pack_rgb332(r, g, b):
    """Quantize an 8-bit RGB triple to one RGB 3-3-2 byte (spec packing)."""
    return (r & 0xE0) | ((g & 0xE0) >> 3) | ((b & 0xC0) >> 6)


def unpack_rgb332(byte):
    """Decode an RGB 3-3-2 byte back to 8-bit RGB using high-bit replication."""
    r3 = (byte >> 5) & 0x07
    g3 = (byte >> 2) & 0x07
    b2 = byte & 0x03
    r = (r3 << 5) | (r3 << 2) | (r3 >> 1)   # 3 bits -> 8 bits
    g = (g3 << 5) | (g3 << 2) | (g3 >> 1)
    b = b2 * 0x55                            # 2 bits -> 8 bits (00,55,AA,FF)
    return (r, g, b)


def sanitize_name(raw):
    """Turn an arbitrary string into a valid C identifier (uppercased)."""
    name = re.sub(r"[^0-9A-Za-z_]", "_", raw).upper()
    if not name or name[0].isdigit():
        name = "_" + name
    return name


def bake(in_path, out_path, width, height, name, resample, preview_path=None,
         preview_scale=4):
    img = Image.open(in_path).convert("RGB")
    img = img.resize((width, height), resample=resample)

    raw = img.tobytes()  # RGB triples, row-major: pixel index = y * width + x
    data = bytes(pack_rgb332(raw[i], raw[i + 1], raw[i + 2])
                 for i in range(0, len(raw), 3))

    guard = sanitize_name(os.path.basename(out_path)) + "_"
    lines = []
    lines.append("/* Generated by bake_asset.py -- do not edit.")
    lines.append(" * Source: %s" % os.path.basename(in_path))
    lines.append(" * Format: RGB 3-3-2, row-major (index = y * %s_W + x)," % name)
    lines.append(" *         matches the FALLOUT GPU framebuffer byte order.")
    lines.append(" */")
    lines.append("#ifndef %s" % guard)
    lines.append("#define %s" % guard)
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("")
    lines.append("#define %s_W %d" % (name, width))
    lines.append("#define %s_H %d" % (name, height))
    lines.append("")
    lines.append("const uint8_t %s[%s_W * %s_H] = {" % (name, name, name))
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append("    " + ", ".join("0x%02X" % b for b in chunk) + ",")
    lines.append("};")
    lines.append("")
    lines.append("#endif /* %s */" % guard)
    lines.append("")

    with open(out_path, "w", newline="\n") as f:
        f.write("\n".join(lines))

    if preview_path:
        rgb = bytearray()
        for b in data:
            rgb.extend(unpack_rgb332(b))
        decoded = Image.frombytes("RGB", (width, height), bytes(rgb))
        decoded = decoded.resize(
            (width * preview_scale, height * preview_scale),
            resample=Image.Resampling.NEAREST,
        )
        decoded.save(preview_path)

    return data


def main(argv=None):
    ap = argparse.ArgumentParser(
        description="Bake a PNG into an RGB 3-3-2 C header for the FALLOUT GPU."
    )
    ap.add_argument("input", help="input PNG (any mode; converted to RGB)")
    ap.add_argument("-o", "--output", default=None,
                    help="output .h path (default: input basename + .h)")
    ap.add_argument("--width", type=int, default=160,
                    help="target width (default 160)")
    ap.add_argument("--height", type=int, default=120,
                    help="target height (default 120)")
    ap.add_argument("--name", default=None,
                    help="C array name (default: derived from output filename)")
    ap.add_argument("--preview", default=None, metavar="PREVIEW.png",
                    help="write the quantized image back as an upscaled PNG")
    ap.add_argument("--resample", choices=("nearest", "lanczos"),
                    default="lanczos",
                    help="resize filter: lanczos (default) or nearest "
                         "(use nearest for pixel art)")
    args = ap.parse_args(argv)

    if args.width <= 0 or args.height <= 0:
        ap.error("--width and --height must be positive")

    out_path = args.output
    if out_path is None:
        out_path = os.path.splitext(args.input)[0] + ".h"

    name = args.name
    if name is None:
        name = sanitize_name(os.path.splitext(os.path.basename(out_path))[0])
    else:
        name = sanitize_name(name)

    resample = (Image.Resampling.NEAREST if args.resample == "nearest"
                else Image.Resampling.LANCZOS)

    data = bake(args.input, out_path, args.width, args.height, name,
                resample, preview_path=args.preview)

    print("baked %s -> %s (%s[%d] = %dx%d RGB332, %d bytes)" % (
        args.input, out_path, name, len(data), args.width, args.height,
        len(data)))
    if args.preview:
        print("preview written to %s" % args.preview)
    return 0


if __name__ == "__main__":
    sys.exit(main())
